CREATE TABLE tb_user (
  id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  telephone VARCHAR(200)  NOT NULL,
  email VARCHAR(200) NOT NULL,
  password VARCHAR(200) NOT NULL,
  cpf VARCHAR(15) NOT NULL
);